info:
  app:
    name : Java Advanced App
    author:
      name: peyman
  company:
    location: tehran




server:
  error:
    whitelabel:
      enabled: true
  servlet:
    context-path: /demo
  port: 80
spring:
  profiles:
    active: dev
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test




---
spring:
  config:
    activate:
      on-profile: production
  jpa:
    hibernate:
      ddl-auto: none
logging:
  level:
    com.peyman.springboot.controller: Info
    com.peyman.springboot.rest: error
    org.springframework.core : error
data:
  value : on production
location : c drive

---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    com.peyman.springboot.controller: trace
    com.peyman.springboot.rest: debug
    org.springframework.core : debug
data:
  value : on dev
location : c drive
